[[plugins]]
package = "netlify-plugin-csp-generator"

  [plugins.inputs]
  buildDir = "dist"
  disablePolicies = "styleSrc"

  [plugins.inputs.policies]
    defaultSrc = "'self'"
    connectSrc="https://api.trello.com https://www.google-analytics.com"
    fontSrc = "'self' https://fonts.gstatic.com"
    scriptSrc ="'unsafe-eval'"
    scriptSrcElem = "'self' 'unsafe-inline' 'unsafe-hashes' 'unsafe-eval' https://www.googletagmanager.com"
    style-src = "'self' 'unsafe-inline' https://fonts.googleapis.com"